image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  #- test

build_project:
  stage: build
  script:
    - npm install
    - npm run lint:ci
    - npm run build:ci
