language: node_js
node_js:
  - "lts/*"
  - "node"
cache:
  directories:
    - "~/.npm"
    #- "node_modules"
script:
  - npm run lint:ci
  - npm run build:ci
  # Ignore tests for now:
  # - npm run test:ci
notifications:
  email: false
